# Generated by Django 5.2.6 on 2025-11-18 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_subgroup_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='invit_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
