# Generated by Django 5.2.6 on 2025-11-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_notification'),
        ('groups', '0003_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.subgroup'),
        ),
    ]
