# Generated by Django 5.2.6 on 2025-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_task_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdocument',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
