# Generated by Django 5.2.6 on 2025-11-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_alter_groupdocument_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdocument',
            old_name='is_pub',
            new_name='is_visible',
        ),
    ]
