# Generated by Django 5.2.6 on 2025-11-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_rename_is_pub_groupdocument_is_visible'),
        ('groups', '0005_subgroup_invit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdocument',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.subgroup'),
        ),
    ]
